import Head from 'next/head'
import Image from 'next/image'
import styles from "../styles/Home.module.scss"
import Content from './Component/Content'
import Header from './Component/Header'
import LeftNav from './Component/LeftNav'
import Table from './Component/Table'

export default function Home() {
  return (
    <div className="heading">
      <Head>
        <title>Lama-Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
    <LeftNav/>
    <Header/>
    <Content/>
    <Table/>
    
    </div>
  )
}
